# fly.toml app configuration file generated for decartography-dashboard on 2023-09-18T18:27:49-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "decartography-dashboard"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
