# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /backend

# Add the current directory contents into the container at /app
ADD . /backend

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libcairo2 \
    libgirepository1.0-dev \
    gcc \
    libpango1.0-0 \
    libpangocairo-1.0-0 \
    gobject-introspection \
    libglib2.0-dev

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python", "backend_app/handlers/handlers.py"]
